apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-helm-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/your-username/my-gitops-repo
        revision: HEAD
        directories:
          - path: apps/nginx/*
  template:
    metadata:
      name: 'nginx-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-username/my-gitops-repo
        targetRevision: HEAD
        path: charts/nginx
        helm:
          valueFiles:
            - ../../apps/nginx/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'nginx-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
